version: '3'

services:
  quote-microservice:
    image: 729108405802.dkr.ecr.us-east-1.amazonaws.com/quote-repo:latest
    ports:
      - '5000:5000'
    networks:
      - prometheus-net

  prometheus:
    image: prom/prometheus
    ports:
      - '9090:9090'
    volumes:
      - ./prometheus:/etc/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    networks:
      - prometheus-net

  grafana:
    image: grafana/grafana
    ports:
      - '3000:3000'
    depends_on:
      - prometheus
    volumes:
      - ./grafana-data:/var/lib/grafana
    networks:
      - prometheus-net
networks:
  prometheus-net:
