version: '3'

services:
  quote-microservice:
    image: ${ECR_REPOSITORY}/quote-repo2:${IMAGE_TAG}
    ports:
      - '80:5000'
    deploy:
      resources:
        limits:
          cpus: '0.5'    # Limit to 50% of a CPU core
          memory: 256M   # Limit to 500MB of memory
    networks:
      - prometheus-net

  prometheus:
    image: prom/prometheus
    user: '1000'
    ports:
      - '9090:9090'
    volumes:
      - ./prometheus:/etc/prometheus
      - ./prometheus-data:/prometheus
    deploy:
      resources:
        limits:
          cpus: '0.5'    # Limit to 50% of a CPU core
          memory: 256M   # Limit to 500MB of memory
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    networks:
      - prometheus-net

  grafana:
    image: grafana/grafana
    user: '1000'
    ports:
      - '3000:3000'
    depends_on:
      - prometheus
    volumes:
      - ./grafana-data:/var/lib/grafana
    deploy:
      resources:
        limits:
          cpus: '0.5'    # Limit to 50% of a CPU core
          memory: 400M   # Limit to 500MB of memory
    networks:
      - prometheus-net

networks:
  prometheus-net:

volumes:
  prometheus-data:
